ingress:
  enabled: true
  hosts:
    -  # Add the IP or "HOSTNAME" here
  path: /

datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: PostgreSQL
      type: postgres
      url: timescaledb-cluster.demo:5432
      access: proxy
      isDefault: true
      user: kafka
      database: kafka
      secureJsonData:
        password: kafka
      jsonData:
        sslmode: require
        tlsConfigurationMethod: file-path
        timescaledb: true

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
