config:
  outputs:
    - influxdb:
        urls:
          - "http://influxdb:8086"
        database: "telegraf"
        skip_database_creation: false
        username: "telegraf"
        password: "telegraf"
  inputs:
    - mqtt_consumer:
        servers:
          - "tcp://rabbitmq:1883"
        data_format: "json"
        topics:
          - "/dpsim-powerflow"
          - "/se"
        username: "admin"
        password: "admin"
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50
          - 95
          - 99
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000
